apiVersion: v1
kind: PersistentVolume
metadata:
  name: vault-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  hostPath:
    path: /mnt/data/vaul
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-pvc
  namespace: ecommerce
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
  namespace: ecommerce
data:
  vault-config.hcl: |
    ui = true
    storage "file" {
      path = "/vault/file"
    }
    listener "tcp" {
      address     = "0.0.0.0:8200"
      tls_disable = 1
    }
    disable_mlock = true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
      - name: vault
        image: hashicorp/vault:1.15.2
        args:
          - "server"
          - "-config=/vault/configmap/vault-config.hcl"
        ports:
        - containerPort: 8200
        volumeMounts:
        - name: vault-config
          mountPath: /vault/configmap
          readOnly: true
        - name: vault-data
          mountPath: /vault/file
      volumes:
      - name: vault-config
        configMap:
          name: vault-config
      - name: vault-data
        persistentVolumeClaim:
          claimName: vault-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: vault
  namespace: ecommerce
spec:
  type: NodePort
  ports:
  - port: 8200
    targetPort: 8200
    nodePort: 30820
  selector:
    app: vault