apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-db
  namespace: ecommerce
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: order-db
  template:
    metadata:
      labels:
        app: order-db
    spec:
      containers:
        - name: order-db
          imagePullPolicy: IfNotPresent
          image: postgres:14
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secrets
                  key: DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secrets
                  key: DB_PASSWORD
            - name: POSTGRES_DB
              value: "order_db"
          volumeMounts:
            - name: order-db-data
              mountPath: /var/lib/postgres/data
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: order-db-data
          persistentVolumeClaim:
            claimName: order-db-pvc
        - name: init-script
          configMap:
            name: order-db-init
      restartPolicy: Always
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: order-db-init
  namespace: ecommerce
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS orders (
      id SERIAL PRIMARY KEY,
      first_name VARCHAR(255) NOT NULL,
      last_name VARCHAR(255) NOT NULL,
      email VARCHAR(255) UNIQUE NOT NULL,
      address VARCHAR(255) NOT NULL,
      date_created TIMESTAMP DEFAULT NOW()
    );
---
apiVersion: v1
kind: Service
metadata:
  name: order-db
  namespace: ecommerce
spec:
  selector:
    app: order-db
  ports: 
    - port: 5432
      targetPort: 5432


